### ISSUE TITLE
Unable to add day off, dialog is empty with error in console.

### ISSUE THREAD

**Issue by FraserKillip** [Microsoft/vsts-team-calendar#189]
I have installed the Calendar plugin on the 7th of November and I am getting the following error when trying to add a 'Day Off'. Adding an event works correctly.

The 'Add Day Off' modal/popup window 'loads' then remains blank. The following error is reported in the console.

```
{
    message: "Cannot read property 'name' of undefined",
    stack: "TypeError: Cannot read property 'name' of undefined
    at https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/0.5.12/1509729228436/dist/Calendar/Dialogs.js:562:63
    at XdmDeferred._wrapCallback (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/0.5.12/1509729228436/dist/vss-web-extension-sdk/VSS.SDK.js:73:26)
    at Array.<anonymous> (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/0.5.12/1509729228436/dist/vss-web-extension-sdk/VSS.SDK.js:48:23)
    at https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/0.5.12/1509729228436/dist/vss-web-extension-sdk/VSS.SDK.js:103:44"
}
```

**Comment by soccerjoshj07** [comment]
It looks like there is no error message. It looks like you need to be a Team Administrator or above to add "Days Off", since it's an extension of the Sprint Capacity section.

**Comment by MattTraxinger** [comment]
I was having the same issue. I was able to click the Days Off Link in the upper right hand corner of the screen to see that I didn't have any iterations assigned. Once I did that the Add Event dialog was populated. Instead of it being blank it should show an appropriate error message.
