### ISSUE TITLE
Calendar fails to load

### ISSUE THREAD

**Issue by bwets** [microsoft/vsts-team-calendar#323]
Mostly the team drop down is empty for some users. In the console, there is clearly an exception related to a team id:

First a 404 on this url:
```
https://telindus.visualstudio.com/_apis/projects/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/teams/fb1b89e9-2900-4f42-b748-d4a89eb1fdeb
```

Then this error
```
Uncaught (in promise) TFS.WebApi.Exception: The team with id 'fb1b89e9-2900-4f42-b748-d4a89eb1fdeb' does not exist, or you do not have permission to access it.
    at Object.<anonymous> (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:24025)
    at https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:22573
    at Object.next (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:22678)
    at a (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:21424)
```

Im project admin, and org admin so permission is not the issue. I believe it relates to a team Id I was part of, then the team was deleted but the id is still in my profile

Any help would be appreciated

**Comment by wemore78** [comment]
I have exactly the same problem. The calendar was working fine, then I removed a team (non-default) that we weren't using anymore and now the calendar view is empty and I can't select the default team :(

**Comment by bwets** [comment]
After digging into the code of the calendar, I have found a workaround that worked for all team members:

- go to https://<INSTANCENAME>.visualstudio.com/_apis/projects/<PROJECTID>/teams

where 
```
INSTANCENAME = your instance
PROJECTID= your project id (should be a guid)
PROJECTNAME = you project Name
```

- From this, you will get a json of all teams and their ids

- Take the guid id of a valid team then go to https://<INSTANCENAME>.visualstudio.com/<PROJECTNAME>/_apps/hub/ms-devlabs.team-calendar.team-calendar?team=<TEAMID>

When you use this link once, the menu entry works permanently

It appears the id of the team you used last time is somehow stored somewhere. 
This of course is just a workaround to get the calendar working again.

**Comment by th-zf** [comment]
Works! Thanks a lot!

**Comment by jamesbr-ashn** [comment]
Appears to be the same as #374
