### ISSUE TITLE
Not able to select any team

### ISSUE THREAD

**Issue by ashu16815** [microsoft/vsts-team-calendar#326]
PFA image 
<img width="1680" alt="Screen Shot 2020-11-18 at 4 57 27 PM" src="https://user-images.githubusercontent.com/25782668/99481537-36370580-29bf-11eb-8e4b-4968d3359619.png">

Failed to load resource: the server responded with a status of 404 ()
Fetch.js:140 Uncaught (in promise) TFS.WebApi.Exception: The team with id '6be1f1e4-14a8-445d-804d-231277724a2f' does not exist, or you do not have permission to access it.
    at Object.<anonymous> (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:24025)
    at https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:22573
    at Object.next (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:22678)
    at a (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:21424)
storage.live.com/Users/0xa59fafa76e84ee7b/MyProfile/ExpressionProfile/ProfilePhoto:Win8Static,UserTileMedium,UserTileStatic/MeControlXXLUserTile?ck=1&ex=24:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by cptskippy** [comment]
Having similar issues.  Did you ever find a solution for this?  Did you have any add-ons or extensions installed that might have caused it?
