### ISSUE TITLE
Cannot view calendar if selected team is removed

### ISSUE THREAD

**Issue by rawrspace** [microsoft/vsts-team-calendar#352]
When trying to access the calendar I am receiving the following error:

```
Fetch.js:140 Uncaught (in promise) TFS.WebApi.Exception: The team with id '333eb0d1-edef-4616-b0bd-fd6170f69bb1' does not exist, or you do not have permission to access it.
    at Object.<anonymous> (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:24025)
    at https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:22573
    at Object.next (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:22678)
    at a (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:21424)
```

My team mate does not receive this error and is able to view the calendar and switch teams.

When the call is made to  `GET https://extmgmt.dev.azure.com/redacted/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/team-calendar/Data/Scopes/User/Me/Collections/%24settings/Documents/selected-team-<GUID>`

The response is:
```
{"id":"selected-team-<GUID>","value":"333eb0d1-edef-4616-b0bd-fd6170f69bb1","__etag":6}
```

That team no longer exists and when the call to `GET https://dev.azure.com/redacted/_apis/projects/<GUID>/teams/333eb0d1-edef-4616-b0bd-fd6170f69bb1` happens it received a 404 and causes the error I posted above.

Is there a way to swtich my selected team programatically? I attempted to change it with postman using my authorization token but that did not seem to work.

Ideally if your selected team results in a 404 then it should proceed with the first available team.

**Comment by rawrspace** [comment]
I was able to capture the request from fiddler on another team when changing my selected team and then replay it with a modified request body to change my selected team on the problematic instance.

This resolved my issue but I still think that it shouldn't crash if your selected team has been deleted.

**Comment by SamGrantham** [comment]
I put this together to work around this issue, it works for me (though I used a high access PAT so I can't tell you the exact scopes required here).  If you don't know the project ID or the team ID you can get them but using the "get" calls in a browser from the RestAPI documentation OR you can get them from an F12/HAR or Fiddler Trace...

Hope this helps someone!

```
$PAT       = '<Your PAT>'
$orgName   = '<OrgName>'
$projectID = '<ProjectID>'
$TeamID    = '<TeamID>'


$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes((":{0}" -f $PAT)))
$responses = $null 
$headers   = $null 
$body      = $null
$params    = $null
$headers   = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("accept-encoding", "gzip, deflate, br")
$headers.Add("authorization", "Basic {0}" -f $base64AuthInfo)
$headers.Add("Content-Type", "application/json")


try {
	$body   = "{`"id`":`"selected-team-$projectID`",`"value`":`"$TeamID`",`"__etag`":-1}"
	$params = @{
        Uri         = "https://extmgmt.dev.azure.com/$orgName/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/team-calendar/Data/Scopes/User/Me/Collections/%24settings/Documents?api-version=3.2-preview.1"
		Headers     = $headers
		Method      = 'PUT'
		Body        = $body 
		ContentType = 'application/json'
	}
	$responses = Invoke-RestMethod @params
	Write-Host $responses
}
Catch {
	Write-Host "ERROR: " -ForegroundColor red
	Write-Host "StatusCode:" $_.Exception.Response.StatusCode.value__ -ForegroundColor red
	Write-Host "StatusDescription:" $_.Exception.Response.StatusDescription -ForegroundColor red
	Write-Host "ErrorDescription:" $_ -ForegroundColor red 
}
```
