### ISSUE TITLE
Sign in required when creating event

### ISSUE THREAD

**Issue by HeinzErnst** [microsoft/vsts-team-calendar#393]
When I open the calendar and try to create an event I am asked to sign in, repeatetly, endless:
![login](https://user-images.githubusercontent.com/10104460/201854569-a9f28c2f-1112-4e79-aa11-dd4d5870609e.PNG)

**Comment by AminTi** [comment]
Thanks for reporting, can you describe your environment? Can you check if you get any errors in the browser console or network log?

**Comment by jjwb96** [comment]
Hi there, 

We have a Project using this extension. It is currently on 2.0.16. We are receiving this exact issue on our environment after upgrading from Azure DevOps Server 2020 Update 1 to Azure DevOps Server 2022 Update 1 and Patch 1 applied. 

I noticed issue #439 where there are two copies of the addon in the marketplace. I don't want to advise the team to install the other addon because I am concerned the data won't port over. 

There is an Uncaught TypeError: Cannont read properties of undefined (reading 'trim'). 
_I took a screenshot, but github kept failing to upload it_

When you cancel out of the prompt it through a 401 error. but its trying to get to <serverurl>/Collection/_apis/ClientTrace/Events

I am not seeing anything stand out in the network logs. 

Any help or guidance would be appreciated.

**Comment by jjwb96** [comment]
Quick follow up. For us, it only appears to be an issue when trying to add a Day off. Creating a regular event works.

**Comment by sebastianlung** [comment]
@AminTi it seems that within Azure DevOps Server 2022, the extension is having issues:
![image](https://user-images.githubusercontent.com/49279609/219604018-b444af9e-d80c-4597-a613-96b7b3d3334c.png)

react.15.3.js:14 Uncaught TypeError: t.uniqueSort is not a function
    at o (widget.js:9:5431)
    at t.<computed>.<computed>._classes (widget.js:9:5677)
    at t.<computed>.<computed>._toggleClass (widget.js:9:6267)
    at t.<computed>.<computed>._addClass (widget.js:9:6059)
    at t.<computed>.<computed>._createWrapper (dialog.js:9:4483)
    at t.<computed>.<computed>._createWrapper (widget.js:9:1143)
    at t.<computed>.<computed>.s (widget.js:9:970)
    at t.<computed>.<computed>._createWrapper (dialog.js:9:12730)
    at t.<computed>.<computed>._createWrapper (widget.js:9:1143)
    at t.<computed>.<computed>._create (dialog.js:9:1658)
o @ widget.js:9
_classes @ widget.js:9
_toggleClass @ widget.js:9
_addClass @ widget.js:9
_createWrapper @ dialog.js:9
(anonymous) @ widget.js:9
s @ widget.js:9
_createWrapper @ dialog.js:9
(anonymous) @ widget.js:9
_create @ dialog.js:9
(anonymous) @ widget.js:9
_createWidget @ widget.js:9
t.<computed>.<computed> @ widget.js:9
(anonymous) @ widget.js:9
each @ jquery.js:374
each @ jquery.js:139
t.fn.<computed> @ widget.js:9
t.initialize @ Dialogs.js:2
t.initialize @ Dialogs.js:2
EditEventDialog.initialize @ main.js:6035
n._attemptInitialize @ Controls.js:2
n.enhance @ Controls.js:2
n.enhance @ Controls.js:2
t.create @ Dialogs.js:2
t.show @ Dialogs.js:2
CalendarView._addEvent @ main.js:20430
CalendarView.addEventClicked @ main.js:20153
CalendarComponent._this._onCommandClick @ main.js:19870
(anonymous) @ main.js:34713
r @ react.15.3.js:14
a @ react.15.3.js:12
s @ react.15.3.js:12
p @ react.15.3.js:12
f @ react.15.3.js:12
r @ react.15.3.js:16
processEventQueue @ react.15.3.js:12
r @ react.15.3.js:14
handleTopLevel @ react.15.3.js:14
i @ react.15.3.js:14
perform @ react.15.3.js:16
batchedUpdates @ react.15.3.js:14
i @ react.15.3.js:15
dispatchEvent @ react.15.3.js:14
ms-devlabs.team-calendar.calendar:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

**Comment by TinaH16** [comment]
I believe @AminTi mentioned in another issue that this would be fixed in an upcoming release. Could you please provide a timeline when we can expect it?

**Comment by bisdevres** [comment]
i have the same problem in version `2.0.22` on Azure DevOps server `2022` (`AzureDevOpsServer_20230306.1`).

these errors are shown in the console log:

`main.js:20961`:
```log
Error getting event data.
Event source: Days off
Reason: Could not load event source Days off. Request timed out.
```

`Validation.js:2`:
```log
Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
    at t.isValid (Validation.js:2:3595)
    at t.validate (Validation.js:2:2903)
    at t.onValidationRequired (Validation.js:2:2802)
    at HTMLBodyElement.<anonymous> (Content?bundle=vss-bundle-ext-core-vnmGFvKW0VS9Hi4wcSHzACpdD-W_BY6jsM5wY0etaIbg=:312:217)
    at HTMLBodyElement.dispatch (jquery.js:4435:9)
    at r.handle (jquery.js:4121:28)
    at Object.trigger (jquery.js:4350:12)
    at HTMLBodyElement.<anonymous> (jquery.js:4901:17)
    at Function.each (jquery.js:374:23)
    at n.fn.init.each (jquery.js:139:17)
```

`/tfs/DevBIS/_apis/ClientTrace/Events:1`:
```log
Failed to load resource: the server responded with a status of 401 (Unauthorized)
```
