### ISSUE TITLE
Team Calendar extension does not work with Azure DevOps Server 2022

### ISSUE THREAD

**Issue by VladimirKhvostov** [microsoft/vsts-team-calendar#410]
Team Calendar extension does not work with Azure DevOps Server 2022.

Here is an error:
```
VSS.SDK.js:105 TypeError: $.uniqueSort is not a function
    at processClassString (widget.js:528:36)
    at $.<computed>.<computed>._classes (widget.js:541:13)
    at $.<computed>.<computed>._toggleClass (widget.js:578:43)
    at $.<computed>.<computed>._addClass (widget.js:566:21)
    at $.<computed>.<computed>._createWrapper (dialog.js:361:14)
    at $.<computed>.<computed>._createWrapper (widget.js:132:37)
    at $.<computed>.<computed>._super (widget.js:117:47)
    at $.<computed>.<computed>._createWrapper (dialog.js:938:18)
    at $.<computed>.<computed>._createWrapper (widget.js:132:37)
    at $.<computed>.<computed>._create (dialog.js:140:14)
```

jQuery.unique() was renamed to uniqueSort in jQuery version 3.0:
https://api.jquery.com/jQuery.uniqueSort/#:~:text=The%20%24.,not%20considered%20to%20be%20duplicates.

Adding the following would fix the issue:
```typescript
if ( !$.uniqueSort ) {
    $.uniqueSort = $.unique;
}
```

**Comment by AminTi** [comment]
Thanks for reporting it will be fixed in an upcoming release.

**Comment by TinaH16** [comment]
Hello @AminTi can you please provide a date for the release to fix this issue? Thanks in advance.

**Comment by dvickerie** [comment]
I too am having an issue with the calendar. Below is a screenshot of the error I am getting:
![image](https://user-images.githubusercontent.com/54188137/233134835-49c4e21f-212b-4296-a838-e29b6383987d.png)

**Comment by joaomarioss** [comment]
the same here. any prevision?

**Comment by AminTi** [comment]
At this moment, we are actively working on the Team Calendar, and once we have resolved it, we will proceed with the release. appreciate your patience.

**Comment by raymondgp** [comment]
Hello @AminTi   would you have any news on this? Is there any plan to get it fixed?
