### ISSUE TITLE
Clicking Add Event button forces user to re-enter credentials

### ISSUE THREAD

**Issue by hauges** [Microsoft/vsts-team-calendar#502]
When clicking the Add Event Button, the user is endlessly asked to enter credentials. The only way to get access back to Azure DevOps is to navigate away from the Calendar page and to enter credentials again.

Azure DevOps deployment is on-prem with Microsoft single sign on.

**Comment by stevekuchta** [comment]
This is probably related to #486. Hopefully we will get an update soon.

**Comment by AminTi** [comment]
thanks for reporting. Could you help us track this down by checking the browser network log (f12 in the browser), and the console log for errors?

**Comment by hauges** [comment]
Here is the console log when attempting to add a new item:

```
react.15.3.js:14  Uncaught TypeError: Cannot read properties of undefined (reading 'getEnhancer')
    at EditEventDialog._createLayout (main.js:6077:30)
    at EditEventDialog.initialize (main.js:6047:18)
    at n._attemptInitialize (Controls.js:2:5674)
    at n.enhance (Controls.js:2:5742)
    at n.enhance (Controls.js:2:2696)
    at t.create (Dialogs.js:2:2964)
    at t.show (Dialogs.js:2:3917)
    at CalendarView._addEvent (main.js:20430:37)
    at CalendarView.addEventClicked (main.js:20153:18)
    at CalendarComponent._this._onCommandClick [as onClick] (main.js:19870:44)
EditEventDialog._createLayout @ main.js:6077
EditEventDialog.initialize @ main.js:6047
n._attemptInitialize @ Controls.js:2
n.enhance @ Controls.js:2
n.enhance @ Controls.js:2
t.create @ Dialogs.js:2
t.show @ Dialogs.js:2
CalendarView._addEvent @ main.js:20430
CalendarView.addEventClicked @ main.js:20153
CalendarComponent._this._onCommandClick @ main.js:19870
(anonymous) @ main.js:34713
r @ react.15.3.js:14
a @ react.15.3.js:12
s @ react.15.3.js:12
p @ react.15.3.js:12
f @ react.15.3.js:12
r @ react.15.3.js:16
processEventQueue @ react.15.3.js:12
r @ react.15.3.js:14
handleTopLevel @ react.15.3.js:14
i @ react.15.3.js:14
perform @ react.15.3.js:16
batchedUpdates @ react.15.3.js:14
i @ react.15.3.js:15
dispatchEvent @ react.15.3.js:14
```

There does not appear to be any errors in the network logs. Every request gets a 200 level response. We did try disabling our single sign on service and it allowed us to add new items, but it still periodically forces us to reenter credentials.
