### ISSUE TITLE
Team Calendar Login Issue

### ISSUE THREAD

**Issue by DEYS** [microsoft/vsts-team-calendar#530]
After upgrading from ADO 2019 to (Version Azure DevOps Server 2022.2 (AzureDevopsServer_20240806.7))
All of our users who attempted to access the team calendar for a project. When clicking on Boards - Calendar, the user is prompted with a Windows Security prompt that states: Sign in.

It prompts for a username and password. If the user enters their network credentials, they are just prompted by the same popup for credentials again. 

Same issue that I see here but this item was closed.
https://github.com/microsoft/vsts-team-calendar/issues/372

Here IS the error I see in the browser devtools tab, we are using Chrome...

Uncaught TypeError: Cannot read properties of undefined (reading 'getEnhancer')
    at EditEventDialog._createLayout (main.js:6077:30)
    at EditEventDialog.initialize (main.js:6047:18)
    at n._attemptInitialize (Controls.js:2:5674)
    at n.enhance (Controls.js:2:5742)
    at n.enhance (Controls.js:2:2696)
    at t.create (Dialogs.js:2:2964)
    at t.show (Dialogs.js:2:3917)
    at CalendarView._addEvent (main.js:20430:37)
    at CalendarView.addEventClicked (main.js:20153:18)
    at CalendarComponent._this._onCommandClick [as onClick] (main.js:19870:44)

Any idea's?

Thank you,
Paul

**Comment by MOlausson** [comment]
@DEYS sorry for the slowness, we're catching up now. Are you still experiencing the problem?

**Comment by DEYS** [comment]
Disabled the extension on our on-prem ADO and are in the process of migrating to the ADO cloud, where it seems to be working.



Thank you,

DEYS







---- On Thu, 04 Sep 2025 04:59:10 -0400 Mathias Olausson ***@***.***> wrote ---



MOlausson left a comment https://github.com/microsoft/vsts-team-calendar/issues/530#issuecomment-3252593088 

https://github.com/DEYS  sorry for the slowness, we're catching up now. Are you still experiencing the problem?
